[package]
name = "flexi_syslog"
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/ObsceneGiraffe/flexi_syslog"
documentation = "https://docs.rs/flexi_syslog"
homepage = "https://crates.io/crates/flexi_syslog"
description = "A syslog writer for flexi_logger"
keywords = ["logger", "logging", "syslog", "flexi-logger"]
categories = ["development-tools::debugging"]

[dependencies]
flexi_logger = { version = "0.22", default_features = false }
syslog = { version = "6.0" }
log = { version = "0.4", features = ["std"] }

[dev-dependencies]
anyhow = { version = "1.0" }