[advisories]
version = 2

[bans]
multiple-versions = "allow"
wildcards = "deny"
# private package can use wildcard paths such as `package.workspace = true`
allow-wildcard-paths = true
deny = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"

[licenses]
version = 2
# We want really high confidence when inferring licenses from text
confidence-threshold = 0.93
# ignore the local workspace crates
private = { ignore = true }
# (extending this list is only allowed after agreement by TD management)
allow = ["Apache-2.0", "MIT"]

[[licenses.exceptions]]
allow = ["Unicode-DFS-2016"]
name = "unicode-ident"
